[project]
name = "api-rest-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Zebi lobognon", email = "zebilobognon@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.20.0",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.141.1",
    "psycopg2-binary>=2.9.13",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.54",
    "uvicorn>=0.52.4",
]

[project.scripts]
api-rest-test = "api_rest_test:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
